package com.asuka.pocketpdf.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 紫色品牌色 — 与 colors.xml / themes.xml 一致
val PurplePrimary = Color(0xFF7652A8)
val PurpleOnPrimary = Color(0xFFFFFFFF)
val PurplePrimaryContainer = Color(0xFFE9DDF4)
val PurpleOnPrimaryContainer = Color(0xFF2E203A)
val PurpleSecondary = Color(0xFF66556F)
val PurpleOnSecondary = Color(0xFFFFFFFF)
val PurpleSecondaryContainer = Color(0xFFE8DEF8)
val PurpleOnSecondaryContainer = Color(0xFF1D192B)
val PurpleTertiary = Color(0xFF7D5260)
val PurpleOnTertiary = Color(0xFFFFFFFF)
val PurpleTertiaryContainer = Color(0xFFFFD8E4)
val PurpleOnTertiaryContainer = Color(0xFF31111D)
val PurpleError = Color(0xFFB3261E)
val PurpleOnError = Color(0xFFFFFFFF)
val PurpleErrorContainer = Color(0xFFF9DEDC)
val PurpleOnErrorContainer = Color(0xFF410E0B)
val PurpleSurface = Color(0xFFF8F5F9)
val PurpleOnSurface = Color(0xFF211C27)
val PurpleSurfaceVariant = Color(0xFFF0EAF3)
val PurpleOnSurfaceVariant = Color(0xFF766F7B)
val PurpleOutline = Color(0xFF8B8190)
val PurpleOutlineVariant = Color(0xFFE4DCE8)
val PurpleBackground = Color(0xFFF0EAF3)
val PurpleOnBackground = Color(0xFF211C27)
val PurpleInverseSurface = Color(0xFF302739)
val PurpleInverseOnSurface = Color(0xFFF8F5F9)
val PurpleInversePrimary = Color(0xFFC4A4ED)
